---
title: "Quiz 1"
author: "S. Servaes"
date: "2/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(ggplot2)
```

## Question 1

```{r question 1}
x <- c(0.18, -1.54, 0.42, 0.95)
w <- c(2, 1, 3, 1)
sum(w*x)/sum(w)
```

## Question 2

```{r question 2}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)
lm(y~x-1)
```

## Question 3

```{r question 3}
data(mtcars)
lm(mpg ~ wt, mtcars)
```

## Question 4

```{r question 4}
slope <- 0.5 * 1/0.5
slope
```

## Question 5

```{r question 5}
slope <- 0.4
0.4*1.5
```

## Question 6

```{r question 6}
x <- c(8.58, 10.46, 9.01, 9.64, 8.86)
xn <- (x - mean(x))/sd(x)
xn[1]
```

## Question 7

```{r question 7}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)
xn <- (x - mean(x))/sd(x)
lm(y ~ x)
```
## Question 8

If the mean is zero of both the predictor and the outcome, the origins are already centered on the mean. Fitting a linear regression to this will result in the intercept being at 0.

## Question 9

```{r question 9}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)

lm(x ~ x)
```

## Question 10


B1 = cor(y, x) * sd(y)/sd(x)
g1 = cor(x, y) * sd(x)/sd(y)

B1/g1 = (cor(y,x) * sd(y)^2) / (cor(x,y) * sd(x)^2) = Var(y)/Var(x)
